client:
  image: schach_client
  stdin_open: true
  tty: true
  net: host

server:
  image: schach_server
  net: host

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example